PROGRAM=lssdp
EXTRA_COMPONENTS=#${ESP_OPEN_RTOS}/extras/i2s_dma ${ESP_OPEN_RTOS}/extras/ws2812_i2s

#CFLAGS+=-DESP -std=c99

include ${ESP_OPEN_RTOS}/common.mk

#all:
#	$(MAKE) -C test

#clean:
#	rm -rf *.o
#	$(MAKE) -C test clean
